### ISSUE TITLE
Question About 'Serial Monitor'

### ISSUE THREAD

**Issue by Rperes** [Sorunome/arduino-upload#1]
Question:
Does  'serial monitor' work only just to report activity from arduino?

I can see all text received from arduino, well formatted but i can't send commands from keyboard to arduino  although see represented on the 'serial Monitor screen! !!!

('arduino-upload packet'  seems work nice and stable with my iMac  OS X Ver 10.11.4.
Tks,
Jose

**Comment by Sorunome** [comment]
I have not implemented sending anything, any idea how it should work UI-wise?

**Comment by Rperes** [comment]
Thanks for your info.
It will be great to use that functionality! 
Rgds.
Jose.

**Comment by Sorunome** [comment]
Do you have an idea how it should look like GUI-wise?
An input box at the bottom of the screen or something?

**Comment by Rperes** [comment]
If you want to give a profissional look, the best ideia for me is . . .  look like the  "Serial Monitor" for the Shell, just with a icon to open/close the working window.

**Comment by Sorunome** [comment]
Added in https://github.com/Sorunome/arduino-upload/releases/tag/v0.6.0
