### ISSUE TITLE
Package can't find Arduino IDE on Linux

### ISSUE THREAD

**Issue by mehalom** [Sorunome/arduino-upload#10]
Program crashes with `'arduino' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.`
Using elementary OS and Arduino IDE 1.8.1

**Comment by Sorunome** [comment]
You need to install the arduino IDE. You won't actually be using the IDE, but it needs to be installed.

**Comment by Sorunome** [comment]
What does `which arduino` output you?

**Comment by mehalom** [comment]
Sorry, I did't catch. What is it?

> `which arduino` output

**Comment by Sorunome** [comment]
Try running
```
which arduino
```
in the terminal and post the ouput ^.^

**Comment by mehalom** [comment]
nothing
 It seems, that the program can't find manually installed Arduino IDE

**Comment by Sorunome** [comment]
Ok, in the package settings edit "Arduino Executable Path" to the absolute path to where the executable of your manual-installed IDE lies.

BTW, why won't you just install the arduino IDE via the repo? That would make things easier ;)

**Comment by mehalom** [comment]
I've installed IDE manually because Ubuntu's repos are very outdated.(

**Comment by Sorunome** [comment]
That's because of the release cycles......anyhow, did you get it to work now?

**Comment by mehalom** [comment]
Not it crashes with `Uncaught Error: spawn EACCES`. (

**Comment by Sorunome** [comment]
do you have any more information on that error? Are you sure you entered the path to the *executable*, not just the folder where it is in?

**Comment by mehalom** [comment]
Rechecked folder, entered path directly to .desktop file. Now it just doesn't recognize connected arduino board (Arduino IDE itself connects normally).

**Comment by Sorunome** [comment]
noooo, you don't enter the path to the .desktop file, you enter the path to the actual executable!

For finding that out you can open your .desktop file with a text editor, somewhere you will have something like `Exec=<something>`, that `<something>` is exactly the path that you'll need to put into the settings

**Comment by mehalom** [comment]
Same issue. Compiler works, but Uploader and Serial monitor not. (Sorry for my stupitidy)

**Comment by Sorunome** [comment]
This is not your stupidity, what you just mentioned might be an actual bug.

May I have the output of
```
lsusb
```
please, while the arduino is plugged in? You are free to only share the arduino line thing.

**Comment by mehalom** [comment]
`Bus 002 Device 003: ID 0424:2514 Standard Microsystems Corp. USB 2.0 Hub
Bus 002 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 005 Device 002: ID 051d:0002 American Power Conversion Uninterruptible Power Supply
Bus 003 Device 002: ID 1a86:7523 QinHeng Electronics HL-340 USB-Serial adapter
Bus 001 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub`
Arduino definitely plugged in and IDE uploads new sketches as usual.

**Comment by Sorunome** [comment]
uuuuh, i can't see from the names which one the arduino is, so could you please send me the output of `lsusb` while the arduino is **not** plugged in additonally?

**Comment by mehalom** [comment]
`Bus 003 Device 003: ID 1a86:7523 QinHeng Electronics HL-340 USB-Serial adapter`
This is the only difference between plugged and unplugged Arduino.

**Comment by Sorunome** [comment]
It should be fixed now, there should be a new update. If it is still broken please create a new issue with the full error message and stuff ^.^
