### ISSUE TITLE
atom-text-editor.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by comfix** [Sorunome/arduino-upload#14]
The contents of `atom-text-editor` elements are no longer encapsulated
within a shadow DOM boundary. Please, stop using `shadowRoot` and access
the editor contents directly instead.
```
atom-text-editor.Object.defineProperty.get (/usr/lib/atom/src/text-editor-element.js:68:18)
<unknown> (/home/comfix/.atom/packages/arduino-upload/lib/serial-view.coffee:44:62)
```

**Comment by Sorunome** [comment]
If you happened to have time to fix this I'd be very grateful, i'm very busy IRL currently ;)

If not, thanks for the issue report, i'll get to it eventually ^.^
