### ISSUE TITLE
error : File isn't part of an Arduino sketch!

### ISSUE THREAD

**Issue by rafaelmmoraes** [Sorunome/arduino-upload#25]
Hey,

Can you help me? I got this error when I try to verify.
"File isn't part of an Arduino sketch!"

thanks

**Comment by Sorunome** [comment]
that means that the currently selected file isn't part of an arduino sketch.

For example, if your main file is called `sketch.ino` that mean that that file `sketch.ino` must be in a folder called `sketch`.

Or, for example `game.ino` must be in a folder called `game`


I hope that helps you out ^.^

**Comment by rafaelmmoraes** [comment]
OKay, but now i have other msg..."'arduino' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process."

**Comment by Sorunome** [comment]
Which OS do you use?

Which version of the Arduino IDE do you have installed?

**Comment by rafaelmmoraes** [comment]
I'm using OS Sierra.

Arduino IDE? it's 1.8.3, but why do i need arduino IDE if i'm using Atom?

**Comment by Sorunome** [comment]
Sierra is....OSX?

This atom plugin invokes the arduino IDE via command line options in a way that it'll never open the gui of it: it needs the arduino ide for compiling and uploading sketches.

As for the issue of `'arduino' could not be spawned.` that basically means that this plugin can't find the arduino IDE. In the settings of arduino-upload you'll see an option `Arduino Executable Path`, enter there the full path to where the arduino executable is. so like `/path/to/arduino`. (Perhaps `/Applications/Arduino.app/Contents/MacOS/Arduino` ?)

If you can't figure that out, i'm sorry I can't help you with that, i don't have any apple machine. However, there is already areport on that open, over here: https://github.com/Sorunome/arduino-upload/issues/13

**Comment by Sorunome** [comment]
And here, too: https://github.com/Sorunome/arduino-upload/issues/4

**Comment by rafaelmmoraes** [comment]
That's great. thanks a lot!

**Comment by Sorunome** [comment]
I think the problem is resolved now, if it isn't then feel free to re-open
