### ISSUE TITLE
Can't upload

### ISSUE THREAD

**Issue by rafaelmmoraes** [Sorunome/arduino-upload#26]
Hi, i'm using a nano atmega 328 in OSX Sierra, i'm able to upload via Arduino IDE but i can't setting my atom to upload.
My port is /dev/wchusbserial1410

could help me?

**Comment by Sorunome** [comment]
Is there any error output? If so, what is it?

**Comment by Sorunome** [comment]
does this problem still exist?

**Comment by StaticRocket** [comment]
@rafaelmmoraes Due to over one year of inactivity, I will mark this issue as closed. Please feel free to respond or reopen it if you still require assistance.
