### ISSUE TITLE
TextEditor.editorElement is deprecated.

### ISSUE THREAD

**Issue by fille044** [Sorunome/arduino-upload#29]
`TextEditor.prototype.editorElement` has always been private, but now
it is gone. Reading the `editorElement` property still returns a
reference to the editor element but this field will be removed in a
later version of Atom, so we recommend using the `element` property instead.
```
TextEditor.editorElement (<embedded>:2381:20)
<unknown> (C:\Users\fille\.atom\packages\arduino-upload\lib\serial-view.coffee:44:42)
```

**Comment by s1monhell** [comment]
is there a solution to this?

**Comment by Triforcey** [comment]
@s1monhell it's nothing to worry about now, but the devs will need to update their code at some point or it may break.
