### ISSUE TITLE
Error: "File isn't part of an Arduino sketch!"

### ISSUE THREAD

**Issue by luisbaldissera** [Sorunome/arduino-upload#3]
Using any of the commands the error "File isn't part of an Arduino sketch!" appears even when it is working on a .ino file inside of its respective sketch folder with the same file name

**Comment by Sorunome** [comment]
Are you triggering the build process via the command palette or the drop-down menu?

**Comment by luisbaldissera** [comment]
command pallete

**Comment by Sorunome** [comment]
hm, which OS are you running & which atom version?

**Comment by luisbaldissera** [comment]
but I tried via drop-down menu and I got the same error

**Comment by luisbaldissera** [comment]
Sorry, I'm begginer but how I see the Atom version? hehe
I'm using Windows 10

**Comment by luisbaldissera** [comment]
In my local Atom folder, there are 3 subfolders: app-1.7.4, app-1.7.3 and app-1.8.0... I suppose I'm using 1.8.0

**Comment by luisbaldissera** [comment]
Ah, yes... now I checked, I'm really using Atom 1.8.0

**Comment by Sorunome** [comment]
Which version of the arduino IDE do you have installed?

**Comment by luisbaldissera** [comment]
Arduino 1.6.9

**Comment by Sorunome** [comment]
Fixed in https://github.com/Sorunome/arduino-upload/commit/20820844c949b4c441ba2381e1974f26f8d6ff44 just update your package

**Comment by hex705** [comment]
This bug seems to be back -- or is for me.
When trying to upload I get the FILE isn't part of sketch error.
The FILE is, really.

All packages updated.
OSX 10.10.5 Yosemite
ATOM 1.23.3
Package 1.3.2
PATH = /Applications/Arduino.app  (note .app required on my system).
Error from command line as well as drop down.
