### ISSUE TITLE
Another Install Issue on Mac OS

### ISSUE THREAD

**Issue by sww1235** [Sorunome/arduino-upload#41]
Hello:

I recently updated to Atom 1.25.0 and along with that attempted to update to Arduino upload 1.33.

The build failed with the log [here](https://gist.github.com/sww1235/6963607465a5092529cfd6ca0cdda4f4)

It looks like it is failing to build due to it requiring a newer version of npm. 

related to #30 and #32

**Comment by jrmedd** [comment]
I'm in the same boat on this. [My log, for the record](https://gist.github.com/jrmedd/6c17e4c3b760e8c0a7c75928836e8ad9).

**Comment by StaticRocket** [comment]
`-- (empty)` indicates the issues reported in #40 are still present. The fall back version is still not set.

**Comment by qoda** [comment]
`sudo npm install -g npm` seemed to do the trick on OSX for me.

**Comment by jrmedd** [comment]
@qoda Can you give any more specific details?

**Comment by jrmedd** [comment]
I realised that my /usr/local/bin/python was symlinked to my Homebrew install of Python 3. I ran brew unlink python and install worked!
