### ISSUE TITLE
Can't open Serial monitor

### ISSUE THREAD

**Issue by xXFloCraftXx** [Sorunome/arduino-upload#43]
I can't open the Serial monitor. The only Error i get is: "Serialport dependency not present, try installing it! (And, if you figure out how, please report me how here as I don't know how to do it..... Really, please help me! D: )". I've tried installing Visual c++ building tools 2015 and Visual c++ building tools 2017. Nothing helped.
I can verify, upload and build but i can't open the serial monitor.
I am using Atom 1.26.1 x64 at Windows 10 x64 (and arduino IDE 1.6.8)
Can anybody help me?

Bye,
Florian

**Comment by wesley-cantarino** [comment]
I too. I don't understand this problem

**Comment by stibinator** [comment]
I'm sure the serial monitor used to work…?

**Comment by CodeJunkieio** [comment]
@FlorianProgrammiert @wesley-cantarino @stibinator This error isn't an error. The developer couldn't get the serial monitor to work, He's telling you to try it for yourself and if you have any luck, let him know so he can fix it.

**Comment by Sorunome** [comment]
what works for me occasionally is uninstalling and re-installing the package.

Also, i really need to move this to the newer serialport versions, if anyone wants to help, that'd be great
