### ISSUE TITLE
Select Arduino board and port manually [enhancement]

### ISSUE THREAD

**Issue by cfvescovo** [Sorunome/arduino-upload#45]
I really like your plugin for Atom and I use it everyday but it would be even better if you added a board and port menu on the bottom bar.

**Comment by Sorunome** [comment]
The board menu is at the bottom bar (it only shows up if you are in a source file of an arduino project) and the port is automatically determined, making the port menu obsolete

**Comment by StaticRocket** [comment]
Duplicate of #36

**Comment by BaldEagleX02** [comment]
@Sorunome If I have 2 Arduino connected to 2 USB ports it doesn't work.
