### ISSUE TITLE
Windows Build Tools Dependency

### ISSUE THREAD

**Issue by StaticRocket** [Sorunome/arduino-upload#52]
Why does this seem to require windows build tools for the initial install? I don't believe it has anything to do with Python and the only way I see it needing MSVS is if something was being compiled during install. Obviously there must be some way to work around this or users would have reported a similar experience with other Atom packages. Submitting this issue for idea spitballing.

**Comment by Sorunome** [comment]
> Why does this seem to require windows build tools for the initial install?

Because of the serialport dependency version this is using (4.0.7, was newest at the time of writing) only provided pre-builts for node.js runtime, not for electron runtime.

The fix would probably be to update to the (by now) newest serialport version, which also provides electron builds. That, unfortunately, takes time I currently don't have. I'd be happy for anyone wanting to help.

**Comment by StaticRocket** [comment]
I'd offer to help, but I have little to no experience with Electron. I wouldn't want to get in the way.

**Comment by Sorunome** [comment]
That shouldn't be a problem, apm does all that stuff for you. So it's only about migrating serialport to newest version (incompatiple APIs)

Am 18. Juli 2018 17:06:14 MESZ schrieb StaticRocket <notifications@github.com>:

**Comment by StaticRocket** [comment]
@Sorunome Well... I'm still working on figuring out where to start with the serialport-builds-electron upgrade, but I think I've solved the serialport installation issue you mentioned in that one error message. I installed it by listing it as a package dependency and sending `Update Package Dependencies: Update` through Atom's Command Palette while in dev mode for the package.

**Comment by Sorunome** [comment]
You'll need the newest serialport package. serialport-builds-electron is my own fork for literally this atom package only, which only provides some more pre-builts.



Am 18. Juli 2018 21:13:14 MESZ schrieb StaticRocket <notifications@github.com>:
