### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by Wermmann** [Sorunome/arduino-upload#57]
I have this issue every time i want to verify or build my arduino code, i don´t now whats wrong, aferter 2 seconds atom says "Build Failed", i have already check the Path and seems to be correct. I've also installed "build-arduino" and "language-arduino" packages. Any suggestion or help will be well appreciated.

> Atom 1.31.0-beta1 x64
arduino-upload 1.3.3
Windows 10 Home Single Language 1803

**Comment by StaticRocket** [comment]
@Wermmann We've made some changes recently, can you tell me if the issue is still present?

**Comment by StaticRocket** [comment]
Closing due to stainless. Please feel free to reopen the issue if it is still a problem.
