### ISSUE TITLE
cant select com port

### ISSUE THREAD

**Issue by SpeedrunnerG55** [Sorunome/arduino-upload#71]
I have multiple boards connected to my computer and normally with the Arduino IDE, I can select what boards I want to upload to. however, there is no obvious way to select the com port in this package.

**Comment by StaticRocket** [comment]
That's a feature I'm planning on adding at some point. See #36

**Comment by SpeedrunnerG55** [comment]
thank you!

**Comment by StaticRocket** [comment]
Closing due to duplicate. Thanks for expressing your interest in this feature, though.
