### ISSUE TITLE
Arduino Debugger Could Not Be Spawned

### ISSUE THREAD

**Issue by RedHoodedWraith** [Sorunome/arduino-upload#72]
I keep getting this error and I'm unsure how to fix it:
"[location to file]\arduino_debug.exe" could not be spawned"

![image](https://user-images.githubusercontent.com/19381986/54168339-d4788580-44d2-11e9-8637-efe30297935a.png)

**Comment by StaticRocket** [comment]
Do you have the Arduino IDE installed, and it's path correctly set in this packages settings?

**Comment by RedHoodedWraith** [comment]
I have now. Turns out I had to install Arduino manually instead of using the Windows Store version and I had to direct it to the directory where I had installed Arduino
