### ISSUE TITLE
Commands not found

### ISSUE THREAD

**Issue by davood-dorostkar** [Sorunome/arduino-upload#73]
I have just installed Arduino-upload package. It works fine but when I open the command bar in atom by pressing ctrl+r, none of the package commands could be found. I can upload the code only be opening "packages-->arduino-upload-->upload", for example.
My system:
     windows 10
     atom 1.35.1 

Why can't I run the commands in commands bar?

![atom](https://user-images.githubusercontent.com/44213441/55290154-a953c880-53e4-11e9-85dc-b14ccef43463.PNG)

**Comment by StaticRocket** [comment]
You're using the wrong keybinding to summon the Command Palette.

| Keystroke | Command | Source |
|---|---|---|
| ctrl-r | symbols-view:toggle-file-symbols | Symbols View |
| ctrl-shift-P | command-palette:toggle | Command Palette |
