### ISSUE TITLE
cant change executable path

### ISSUE THREAD

**Issue by SpeedrunnerG55** [Sorunome/arduino-upload#74]
I can't change the executable path for the Arduino IDE. I don't see it in settings.

**Comment by Sorunome** [comment]
In the settings for this extension it's tge one called `Arduino Executable Path`

Am 2. Mai 2019 21:57:54 MESZ schrieb SpeedrunnerG55 <notifications@github.com>:

**Comment by SpeedrunnerG55** [comment]
I just realized I don't see settings for this package at all 
https://imgur.com/tZr7JxP

**Comment by SpeedrunnerG55** [comment]
uninstalling and reinstalling brought it back. sry.
